Modified lint workflow to remove lint_success consolidation job (#4)
* Modified lint workflow to remove lint_success consolidation job

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Modified lint workflow to comment out source file filtering for testing

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Added CI workflow for ROS 2 build and test

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* (Reading database ... 125271 files and directories currently installed.)
Preparing to unpack .../ros-humble-hardware-interface-testing_2.53.1-1jammy.20260304.231045_amd64.deb ...
Unpacking ros-humble-hardware-interface-testing (2.53.1-1jammy.20260304.231045) ...
Setting up ros-humble-hardware-interface-testing (2.53.1-1jammy.20260304.231045) ...
Reading package lists...
Building dependency tree...
Reading state information...
ros-humble-ros2-control-test-assets is already the newest version (2.53.1-1jammy.20260304.195056).
ros-humble-ros2-control-test-assets set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
executing command [apt-get install -y ros-humble-ros2-control]
executing command [apt-get install -y ros-humble-controller-manager]
executing command [apt-get install -y ros-humble-joint-state-publisher]
executing command [apt-get install -y ros-humble-xacro]
executing command [apt-get install -y ros-humble-coin-d4-driver]
executing command [apt-get install -y ros-humble-ublox-gps]
executing command [apt-get install -y ros-humble-joint-state-broadcaster]
executing command [apt-get install -y ros-humble-rviz-imu-plugin]
executing command [apt-get install -y ros-humble-dynamixel-sdk]
executing command [apt-get install -y ros-humble-joint-state-publisher-gui]
executing command [apt-get install -y ros-humble-hardware-interface]
executing command [apt-get install -y ros-humble-orbbec-camera]
executing command [apt-get install -y ros-humble-generate-parameter-library]
executing command [apt-get install -y ros-humble-ros2-control-cmake]
executing command [apt-get install -y ros-humble-controller-interface]
executing command [apt-get install -y ros-humble-realtime-tools]
executing command [apt-get install -y ros-humble-hardware-interface-testing]
executing command [apt-get install -y ros-humble-ros2-control-test-assets]
#All required rosdeps installed successfully
--- Performing rosdep check for ROS 2 humble ---
ERROR[antbot_teleop]: Cannot locate rosdep definition for [ament_python]
All system dependencies have been satisfied
	rosdep key : ament_python
	OS name    : ubuntu
	OS version : jammy
	Data:
<no data>
--- rosdep check failed: Missing system dependencies or unresolvable keys. ---
Error: Process completed with exit code 1.

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Modified ros-ci.yml to skip antbot_camera build due to ARM-only librectrl.so dependency

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Fixed CI build failure caused by comment syntax in package-name field

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Added packages-skip option to exclude antbot_camera from CI build

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Added antbot_bringup to packages-skip due to antbot_camera dependency

Signed-off-by: SungHyeon Oh <osh@robotis.com>

* Modified CI to build all workspace packages instead of specifying package-name

Signed-off-by: SungHyeon Oh <osh@robotis.com>

---------

Signed-off-by: SungHyeon Oh <osh@robotis.com>